library(ISwR)
require(dplyr)
require(reshape2)
library(caret)
attach(rmr)


names(rmr)
lm(metabolic.rate ~ body.weight)
summary(lm(metabolic.rate ~ body.weight))
plot(body.weight, metabolic.rate )
abline(lm(metabolic.rate ~ body.weight))

options(na.action = na.exclude)
lm.velo <- lm(metabolic.rate ~ body.weight)
fitted(lm.velo)
resid(lm.velo)
lines(metabolic.rate, fitted(lm.velo))
segments(body.weight, fitted(lm.velo), body.weight, metabolic.rate)
abline(lm(metabolic.rate ~ body.weight))