setwd("/home/tomaz/Documentos/R\ Teste/Tomaz\ Bisneto\ /")
dados <- read.csv("OnlineNewsPopularity.csv",header = TRUE)
#str(dados)
#summary(dados)
domingos <- subset(dados,dados["weekday_is_sunday"]==1.0)
segundas <- subset(dados,dados["weekday_is_monday"]==1.0)
terca <- subset(dados,dados["weekday_is_tuesday"]==1.0)
quarta <- subset(dados,dados["weekday_is_wednesday"]==1.0)
quinta <- subset(dados,dados["weekday_is_thursday"]==1.0)
sexta <- subset(dados,dados["weekday_is_friday"]==1.0)
sabado <- subset(dados,dados["weekday_is_saturday"]==1.0)
#Valores das Medias 
media_domingos = mean(domingos$shares,na.rm = TRUE)
media_segundas = mean(segundas$shares,na.rm = TRUE)
media_terca = mean(terca$shares,na.rm = TRUE)
media_quarta = mean(quarta$shares,na.rm = TRUE)
media_quinta = mean(quinta$shares,na.rm = TRUE)
media_sexta = mean(sexta$shares,na.rm = TRUE)
media_sabado = mean(sabado$shares,na.rm = TRUE)
#Valores d
desvio_domingos = sd(domingos$shares,na.rm = TRUE)
desvio_segundas = sd(segundas$shares,na.rm = TRUE)
desvio_terca = sd(terca$shares,na.rm = TRUE)
desvio_quarta = sd(quarta$shares,na.rm = TRUE)
desvio_quinta = sd(quinta$shares,na.rm = TRUE)
desvio_sexta = sd(sexta$shares,na.rm = TRUE)
desvio_sabado = sd(sabado$shares,na.rm = TRUE)

#Construindo as listas Para plot
medias <-  c(media_domingos,media_segundas,media_terca,media_quarta,media_quinta,media_sexta,media_sabado)
desvios_padroes <- c(desvio_domingos,desvio_segundas,desvio_terca,desvio_quarta,desvio_quinta,desvio_sexta,desvio_sabado)
dias_da_Semana <- c("Domingo","Segunda-Feira","Terça-Feira","Quarta-Feira","Quinta-Feira","Sexta-Feira","Sabado")
d = c(1,2,3,4,5,6,7)

#Plotagem do Grafico 
str(desvios_padroes)
plot(medias~d,type = "o", xaxt = "n",col = "blue", lwd =1,main = "Compartilhamento de Noticias Pela Internet ",ylim = c(3000,4500),xlab = "Dias de Semana",ylab = "Quantidade de Compartilhamento",lty =2,pch =1,sub = "Meidas de Compartilhamento")
axis(1,at = d,labels = dias_da_Semana)
legend(x=4,y=4500,legend = c("Media Compartilhada"),col = c("blue"),lty=2, cex=0.6,title = "Legendas")
